//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TuningStudio.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Autopart
    {
        public int ID { get; set; }
        public string Unit { get; set; }
        public int GuaranteeMonth { get; set; }
        public int ManufacturerID { get; set; }
        public int TypeOfWorkID { get; set; }
    
        public virtual Manufacturer Manufacturer { get; set; }
        public virtual TypeOfWork TypeOfWork { get; set; }
    }
}
