//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TuningStudio.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int TypeOfWorkID { get; set; }
        public int VehicleID { get; set; }
        public Nullable<bool> IsAccepted { get; set; }
        public Nullable<System.DateTime> DateOfOrder { get; set; }
    
        public virtual TypeOfWork TypeOfWork { get; set; }
        public virtual Vehicle Vehicle { get; set; }
    }
}
